//
// Created by hapq on 19/1/2023.
//
#ifndef NETWORKPROGRAMMING_PROTOCOL_H
#define NETWORKPROGRAMMING_PROTOCOL_H

typedef enum {
    LOGIN,
    REGISTER,
    LOGOUT,
    
    SHOW_LIST_PLACES,
    SHOW_LIST_FAVORITE_PLACES,
} REQUEST_CODE;


typedef enum {
    SHOW_LIST_PLACES_FAIL,
    NUM_PLACES,
    SHOW_PLACE,

    QUERY_FAIL,

    USERNAME_NOTFOUND,
    USERNAME_BLOCKED,
    USERNAME_IS_SIGNIN,

    PASSWORD_INCORRECT,

    LOGIN_SUCCESS,

    LOGOUT_SUCCESS,
    LOGOUT_FAIL,

    REGISTER_SUCCESS,
    REGISTER_USERNAME_EXISTED,
} RESPONSE_CODE;

#endif //NETWORKPROGRAMMING_PROTOCOL_H
