#ifndef NETWORKPROGRAMMING_PROTOCOL_H
#define NETWORKPROGRAMMING_PROTOCOL_H

typedef enum {
    LOGIN,
    REGISTER,
    LOGOUT,

    SHOW_LIST_PLACES,
    SHOW_LIST_FAVORITE_PLACES,
    ADD_FAVARITE_PLACE,
    SHOW_LIST_USER,
    SHARE_PLACE,
    SHOW_SHARED_PLACE,
    SHOW_LIST_FRIEND,

    ADD_PLACE,

    DELETE_FAVORITE_PLACE,

    SHOW_LIST_FRIEND_REQUEST,

    ADD_FRIEND,
    ACCEPT_FRIEND,
    DENY_FRIEND,
    REMOVE_FRIEND,

    BACKUP,
    RESTORE,
} REQUEST_CODE;


typedef enum {
    SHOW_LIST_FAIL,
    NUM_PLACES,
    SHOW_PLACE,

    QUERY_FAIL,

    USERNAME_NOT_FOUND,
    USERNAME_BLOCKED,
    USERNAME_IS_SIGNIN,

    PASSWORD_INCORRECT,

    LOGIN_SUCCESS,

    LOGOUT_SUCCESS,
    LOGOUT_FAIL,

    REGISTER_SUCCESS,
    REGISTER_USERNAME_EXISTED,

    ADD_FAVARITE_PLACE_SUCCESS,
    ADD_FAVARITE_PLACE_FAIL,

    NUM_FAVORITE_PLACES,
    SHOW_FAVORITE_PLACE,

    NUM_USER,
    SHOW_USER,

    SHARE_SUCCESS,
    SHARE_FAIL,

    NUM_SHARED_PLACE,
    SHOW_SHARED_PLACE_SUCCESS,

    NUM_FRIEND,

    ADD_PLACE_SUCCESS,
    ADD_PLACE_FAIL,

    DELETE_FAVORITE_PLACE_SUCCESS,
    DELETE_FAVORITE_PLACE_FAIL,

    NUM_FRIEND_REQUESTS,

    REQUEST_SUCCESS,
    REQUEST_FAIL,

    BACKUP_SUCCESS,
    RESTORE_SUCCESS,

} RESPONSE_CODE;

#endif //NETWORKPROGRAMMING_PROTOCOL_H
